
# Final Render.yaml Configuration

# API Service
services:
- type: web
  name: lago-api
  runtime: docker
  envVars:
    - key: POSTGRES_DB
      value: lago
    - key: POSTGRES_USER
      value: lago
    - key: POSTGRES_PASSWORD
      value: changeme
    - key: POSTGRES_PORT
      value: 5432
    - key: REDIS_PORT
      value: 6379

# Redis Service
- type: redis
  name: lago-redis
  ipAllowList:
    - source: 0.0.0.0/0
      description: everywhere

# PostgreSQL Database
databases:
  - name: lago-postgres
    postgresMajorVersion: 14
